### ISSUE TITLE
Rasa Core Error: Connection Refused (Cisco AnyConnect/Docker Issue?)

### ISSUE THREAD

**Issue by plambe8** [pradeepmvn/rasa_stack_quickstart#3]
Hello! Thank you for this wonderful repo, it really is amazingly useful for us. I have randomly ran into an issue and I am unsure what's causing it. When I run docker-compose up to run the application, Rasa Core does not connect to the endpoint properly: the connection is refused. Here is the log:

```
rasa-ui_1         | > RasaUI@0.2.0 start /opt/rasaui
rasa-ui_1         | > node server/server.js
rasa-ui_1         | 
rasa-ui_1         | Rasa UI Server: http://localhost:5001
rasa-ui_1         | 
rasa-ui_1         | Express server listening on port 5001
rasa-core_1       | WARNING:py.warnings:/usr/local/lib/python3.5/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
rasa-core_1       |   from ._conv import register_converters as _register_converters
rasa-core_1       | 
rasa-nlu_1        | 2018-07-13 16:56:09+0000 [-] "172.19.0.5" - - [13/Jul/2018:16:56:08 +0000] "GET /config HTTP/1.1" 200 666 "-" "-"
rasa-ui_1         | 
**rasa-ui_1         | Rasa Core Error: Error: connect ECONNREFUSED 172.19.0.4:5005
rasa-ui_1         | Using connection string from: process.env.rasacoreendpoint**
rasa-ui_1         | 
rasa-ui_1         | 
rasa-ui_1         | Rasa NLU Connected
rasa-ui_1         | Using connection string from: process.env.rasanluendpoint
rasa-ui_1         | Rasa NLU Server: http://rasa-nlu:5000
rasa-ui_1         | 
rasa-ui_1         | 
rasa-ui_1         | Postgres DB Connected
rasa-ui_1         | Using connection string from: package.json
rasa-ui_1         | Postgres Server: null:null
rasa-ui_1         | Database:rasaui
rasa-ui_1         | Schema:public
rasa-ui_1         | 
rasa-core_1       | 2018-07-13 16:56:10.672874: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
rasa-core_1       | 2018-07-13 16:56:10+0000 [-] Log opened.
rasa-core_1       | 2018-07-13 16:56:10+0000 [-] Site starting on 5005
rasa-core_1       | 2018-07-13 16:56:10+0000 [-] Starting factory <twisted.web.server.Site object at 0x7f1431d31f28>
```

I was messing with some things when this happened, but upon the reversion of those changes it didn't correct itself. I should note that the issues started when I used Cisco AnyConnect as I am currently on the network using the VPN. However, disconnecting that doesn't seem to fix the issue now. 

Things I have tried:

- changing the port number from 5005 to 5006 and reflecting this everywhere else in the project code
- disconnecting from the VPN and running again
- pulling the repo fresh and running again
- manually running docker kill on all processes and port connections, and running again 

Out of 50+ attempts at re-running the docker-compose up command since this issue started occurring, it successfully connected once. Then it promptly failed again next time. I suspect the VPN has messed with the routes in some permanent way that I need to correct.

Please let me know if I can supply more information! Thank you  

edit:
Have found this post: https://stackoverflow.com/questions/41739675/unable-to-connect-to-docker-on-anyconnect-vpn

Will look into those solutions and update if I solve it 

edit2: 
Alright I'm back...no success. 

Things I've Tried Part 2:
- Closing VPN session entirely. 
- Removing all containers, images, bridges, networks, etc. Everything, fresh clean and then rebuilt. Same thing

So either the VPN messed something up so deeply that I cannot figure it out, or its a red herring..because now the VPN isn't even running and the issue persists!

**Comment by pradeepmvn** [comment]
@plambe8 Can you make sure Enviroment variable for rasa-ui in docker-compose file has the service reference "rasa-core" instead of ip address 
```
rasacoreendpoint=http://rasa-core:5005
```

**Comment by plambe8** [comment]
Yup, it says exactly what you wrote.....which is very weird given what the console is outputting. I think it's some routing thing with AnyConnect

**Comment by plambe8** [comment]
I tried creating a .env file and setting it through that, but it didn't change anything for me.

**Comment by plambe8** [comment]
Well......re-installing Docker worked! Didn't want to believe that would work but it did.
