### ISSUE TITLE
From where the data of weather graped?

### ISSUE THREAD

**Issue by tushar1328** [pradeepmvn/rasa_stack_quickstart#4]
From where the data of weather graped?
Does the webhook call any api?
I didn't any API here. Can you please show me some way?

**Comment by pradeepmvn** [comment]
@tushar1328 It call s Yahoo Weather API with YQL. This project should have those details.
https://github.com/pradeepmvn/rasa_stack_quickstart/tree/master/weatherbot/weatherbot-api
