### ISSUE TITLE
rasa-core - docker build error in step #9

### ISSUE THREAD

**Issue by krisand** [pradeepmvn/rasa_stack_quickstart#6]
I am not building the docker image using docker-compose file. But, building the individual ones using the respective docker file under core, nlu and ui.
When I built the rasa-core image using Jenkins and it failed on the below step. 
I fixed it by removing one of the "RUN" from the command and jenkins job moved on from that error. (i used my own copy of this repo to fix it).   Is this fix suppose to be here too ? I was not sure,  

Here is the error.
Step 9/15 : RUN RUN python -m pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.8.0-cp35-cp35m-linux_x86_64.whl
 ---> Running in 48e2f28061af
[91m/bin/sh: 1: RUN: not found

**Comment by JohnMatty** [comment]
fix was merged

**Comment by JohnMatty** [comment]
removed the extra RUN command

**Comment by Cec-lia** [comment]
how did u build the individual ones??
