### ISSUE TITLE
OSE unable to start rasa-ui, which is built using the docker file

### ISSUE THREAD

**Issue by krisand** [pradeepmvn/rasa_stack_quickstart#8]
We get the error, if we use the docker file for building and deploying in OSE.

chmod: changing permissions of '/var/run/postgresql': Operation not permitted
--

**Comment by pradeepmvn** [comment]
@krisand did you get this resolved?
OSE cannot run a root user. You need to modify it to explicitly give permissions to the Postgres data directories.

**Comment by JohnMatty** [comment]
@pradeepmvn yes, I have resolved this. I have modified the id/pwd, server name and port etc.. Then rasa ui connected to the postgres database.
